apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-application-deployment
  labels:
    app: server-application
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: server-application
  template:
    metadata:
      labels:
        app: server-application
    spec:
      containers:
        - name: server-container
          image: 022071580777.dkr.ecr.us-east-1.amazonaws.com/developmentproject:latest
          ports:
            - name: server-port
              containerPort: 3000
              protocol: TCP
